#if !canImport(ObjectiveC)
import XCTest

extension AlgorithmsTestCase {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AlgorithmsTestCase = [
        ("testCollectionLongestSubrange", testCollectionLongestSubrange),
        ("testCollectionSplitEmpty", testCollectionSplitEmpty),
        ("testCollectionSplitExact", testCollectionSplitExact),
        ("testCollectionSplitRemainder", testCollectionSplitRemainder),
        ("testCollectionTrim", testCollectionTrim),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(AlgorithmsTestCase.__allTests__AlgorithmsTestCase),
    ]
}
#endif
