// Copyright The swift-url Contributors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

@usableFromInline
protocol CodePointDatabaseSchema {

  /// The type of data that is stored for ASCII code-points.
  associatedtype ASCIIData

  /// The type of data that is stored for non-ASCII code-points.
  associatedtype UnicodeData
}

@usableFromInline
protocol CodePointDatabaseBuildSchema: CodePointDatabaseSchema {

  static var asciiEntryElementType: String { get }
  static func formatASCIIEntry(_ entry: ASCIIData) -> String

  static var unicodeEntryElementType: String { get }
  static func formatUnicodeEntry(_ entry: UnicodeData) -> String

  static func entry(_ entry: UnicodeData, copyForStartingAt newStartPoint: UInt32) -> UnicodeData
}

extension CodePointDatabaseBuildSchema {

  @inlinable
  static func entry(_ entry: UnicodeData, copyForStartingAt newStartPoint: UInt32) -> UnicodeData {
    // Default assumption is that entries do not care which code-points they apply to.
    entry
  }
}

// swift-format-ignore
/// A static database of information about Unicode code-points.
///
/// Databases are generated by a `Database.Builder`, which produces a Swift source file.
/// Data is stored in 3 sections:
///
/// - A direct lookup for ASCII code-points, to values of the `Entry.ASCIIEntry` type.
///
/// - A 4:12 2-stage lookup for BMP code-points, to values of the `Entry.UnicodeEntry` type.
///
/// - A per-plane lookup table for non-BMP code-points, using compressed 16-bit entries,
///   to values of the `Entry.UnicodeEntry` type.
///
@usableFromInline
internal struct CodePointDatabase<Schema: CodePointDatabaseSchema> {

  @usableFromInline
  internal typealias SplitTable<CodePoint, Data> = (codePointTable: [CodePoint], dataTable: [Data])

  @usableFromInline internal var _asciiData : [Schema.ASCIIData]
  @usableFromInline internal var _bmpData   : [SplitTable<UInt16, Schema.UnicodeData>]
  @usableFromInline internal var _nonbmpData: [SplitTable<UInt16, Schema.UnicodeData>]

  /// Initializes a database from static data.
  ///
  @inlinable
  internal init(
    asciiData : [Schema.ASCIIData],
    bmpData   : [SplitTable<UInt16, Schema.UnicodeData>],
    nonbmpData: [SplitTable<UInt16, Schema.UnicodeData>]
  ) {
    self._asciiData = asciiData
    self._bmpData = bmpData
    self._nonbmpData = nonbmpData
    #if DEBUG
      validateStructure()
    #endif
  }
}


// --------------------------------------------
// MARK: - Structure Validation
// --------------------------------------------


extension CodePointDatabase {

  /// Validates basic structural information about the database.
  ///
  /// This function does not perform any validation of data associated with code points,
  /// nor does it check that code-point tables are sorted (as they are expected to be).
  ///
  @usableFromInline
  internal func validateStructure() {
    do {
      precondition(_asciiData.count == 128)
      precondition(_bmpData.count == 16)
      precondition(_nonbmpData.count == 16)
    }
    // Check that the lengths of the split arrays are equal.
    // This means a valid position in the index table is a valid position in the entry table,
    // and we don't need to bounds-check when using a position from one table in the other table.
    do {
      for splitTable in _bmpData {
        precondition(
          splitTable.codePointTable.count == splitTable.dataTable.count,
          "The split index and entry tables must have the same number of elements"
        )
      }
      for splitTable in _nonbmpData {
        precondition(
          splitTable.codePointTable.count == splitTable.dataTable.count,
          "The split index and entry tables must have the same number of elements"
        )
      }
    }
    // Every plane/sub-plane table must have at least one entry, for the start of the plane/sub-plane.
    do {
      var bmpIter = _bmpData.enumerated().makeIterator()
      precondition(bmpIter.next()?.element.codePointTable[0] == 0x80, "The first BMP sub-plane should start at 0x80")
      while let (subplane, splitTable) = bmpIter.next() {
        precondition(splitTable.codePointTable[0] == (subplane << 12))
      }
      for splitTable in _nonbmpData {
        precondition(splitTable.codePointTable[0] == 0)
      }
    }
  }
}


// --------------------------------------------
// MARK: - Reading
// --------------------------------------------


extension CodePointDatabase {

  @usableFromInline
  internal enum LookupResult {

    /// The data associated with an ASCII code-point.
    ///
    /// Each data value is associated with a single code-point.
    ///
    case ascii(Schema.ASCIIData)

    /// The data associated with a non-ASCII code-point.
    ///
    /// A single data value may represent a range of code-points.
    /// `startCodePoint` gives the code-point at which this data value starts to apply.
    ///
    case nonAscii(Schema.UnicodeData, startCodePoint: UInt32)
  }

  @inlinable
  internal subscript(scalar: Unicode.Scalar) -> LookupResult {
    if scalar.isASCII {
      return .ascii(_asciiData.withUnsafeBufferPointer { buf in buf[Int(scalar.value)] })
    }
    if scalar.value < 0x01_0000 {
      return _bmp_withIndexAndDataTable(containing: scalar) {
        codePointTable, dataTable, offsetWithinBMP in
        let k = codePointTable._codepointdatabase_partitionedIndex { offsetWithinBMP >= $0 } &- 1
        return .nonAscii(dataTable[k], startCodePoint: UInt32(codePointTable[k]))
      }
    }
    return _nonbmp_withIndexAndDataTable(containing: scalar) {
      codePointTable, dataTable, planeStart, offsetWithinPlane in
      let k = codePointTable._codepointdatabase_partitionedIndex { offsetWithinPlane >= $0 } &- 1
      return .nonAscii(dataTable[k], startCodePoint: planeStart | UInt32(codePointTable[k]))
    }
  }

  // Note: The BMP codepoint table stores full scalar values in its 16 bits, since BMP scalars are only 16 bit.
  //       In other words, 0x0ABC, 0x1ABC, and 0x2ABC are stored like that in the code-point table,
  //       rather than being stored like "offset: 0x0ABC in table: 0/1/2/...".
  @inlinable
  internal func _bmp_withIndexAndDataTable<T>(
    containing scalar: Unicode.Scalar,
    body: (
      _ codePointTable: UnsafeBufferPointer<UInt16>,
      _ dataTable: UnsafeBufferPointer<Schema.UnicodeData>,
      _ offsetWithinBMP: UInt16
    ) -> T
  ) -> T {
    let offsetWithinBMP = UInt16(truncatingIfNeeded: scalar.value)
    let subplane = offsetWithinBMP &>> 12
    return _bmpData.withUnsafeBufferPointer { subplaneSplitTables in
      let dataForSubplane = subplaneSplitTables[Int(subplane)]
      return dataForSubplane.codePointTable.withUnsafeBufferPointer { codePointTable in
        return dataForSubplane.dataTable.withUnsafeBufferPointer { dataTable in
          return body(codePointTable, dataTable, offsetWithinBMP)
        }
      }
    }
  }

  @inlinable
  internal func _nonbmp_withIndexAndDataTable<T>(
    containing scalar: Unicode.Scalar,
    body: (
      _ codePointTable: UnsafeBufferPointer<UInt16>,
      _ dataTable: UnsafeBufferPointer<Schema.UnicodeData>,
      _ planeStart: UInt32, _ offsetWithinPlane: UInt16
    ) -> T
  ) -> T {
    let (plane, offsetWithinPlane) = (scalar.value &>> 16, UInt16(truncatingIfNeeded: scalar.value))
    let planeStart = plane &<< 16
    return _nonbmpData.withUnsafeBufferPointer { planeSplitTables in
      let dataForPlane = planeSplitTables[Int(plane &- 1)]
      return dataForPlane.codePointTable.withUnsafeBufferPointer { codePointTable in
        return dataForPlane.dataTable.withUnsafeBufferPointer { dataTable in
          return body(codePointTable, dataTable, planeStart, offsetWithinPlane)
        }
      }
    }
  }
}

extension CodePointDatabase.LookupResult where Schema.ASCIIData == Schema.UnicodeData {

  @inlinable
  internal var value: Schema.ASCIIData {
    switch self {
    case .ascii(let v): return v
    case .nonAscii(let v, startCodePoint: _): return v
    }
  }
}

extension RandomAccessCollection {

  /// Returns the index of the first element in the collection
  /// that doesn't match the predicate.
  ///
  /// The collection must already be partitioned according to the
  /// predicate, as if `x.partition(by: predicate)` had already
  /// been called.
  ///
  @inlinable
  internal func _codepointdatabase_partitionedIndex(where predicate: (Element) -> Bool) -> Index {
    var low = self.startIndex
    var high = self.endIndex
    while low < high {
      let mid = index(low, offsetBy: distance(from: low, to: high) / 2)
      if predicate(self[mid]) {
        low = index(after: mid)
      } else {
        high = mid
      }
    }
    return low
  }
}


// --------------------------------------------
// MARK: - Generating Static Databases
// --------------------------------------------


#if UNICODE_DB_INCLUDE_BUILDER

  extension CodePointDatabase where Schema: CodePointDatabaseBuildSchema {

    /// For the builder only. Creates an empty database.
    ///
    fileprivate init() {
      _asciiData = []
      _bmpData = (0x00...0x0F).map { _ in (codePointTable: [], dataTable: []) }
      _nonbmpData = (0x01...0x10).map { _ in (codePointTable: [], dataTable: []) }
    }

    /// A builder for a static database of information about Unicode code-points.
    ///
    /// Append entries to the database in code-point order, starting with `appendAscii` at code-point 0 (`U+0000`),
    /// appending individual entries for each of the 128 ASCII code-points.
    ///
    /// Next, call `appendUnicode`, starting at code-point 128 (`U+0080`). You may append entries for ranges of
    /// code-points at a time, but each range must be immediately follow the one that came before:
    ///
    /// ```swift
    /// appendUnicode(entryUno, 0x0080...0xABAB)
    /// appendUnicode(entryDuo, 0xABAC...0xCDCD)
    /// appendUnicode(entryTri, 0xCDCE...0xEFEF)
    /// appendUnicode(entryQut, 0xEFF0...0x10FFFF)
    /// ```
    ///
    /// You must finish with an entry that includes the maximum code-point, `0x10FFFF`.
    ///
    internal struct Builder {
      private var db: CodePointDatabase
      private var top: UInt32

      internal init() {
        db = CodePointDatabase()
        top = 0
      }

      internal func finalize() -> CodePointDatabase {
        precondition(top - 1 == 0x10FFFF, "Entries must be inserted up to (including) 0x10FFFF")
        db.validateStructure()
        return db
      }

      internal mutating func appendAscii(_ data: Schema.ASCIIData, for codePoint: UInt32) {
        // Validate insertion.
        precondition(top == codePoint, "Inserting ASCII entry in wrong location!")
        precondition(codePoint < 128, "\(codePoint) is not an ASCII code-point")
        top += 1

        // Insert.
        db._asciiData.append(data)
      }

      internal mutating func appendUnicode(_ data: Schema.UnicodeData, for codePoints: ClosedRange<UInt32>) {
        // Validate insertion.
        precondition(top == codePoints.lowerBound, "Inserting Unicode entry in wrong location!")
        precondition(codePoints.lowerBound >= 0x80, "\(codePoints.lowerBound) is ASCII; use appendAscii instead")
        precondition(codePoints.lowerBound < 0x10FFFF, "\(codePoints.lowerBound) is not a valid Unicode code-point")
        precondition(codePoints.upperBound <= 0x10FFFF, "\(codePoints.upperBound) is not a valid Unicode code-point")
        top = codePoints.upperBound + 1

        // Insert.

        func addToPlaneTable(
          _ table: inout SplitTable<UInt16, Schema.UnicodeData>, planeRange: ClosedRange<UInt32>
        ) -> Bool {

          if codePoints.contains(planeRange.lowerBound) {
            // Crossing to a new plane table means we may need to split/copy the data.
            assert(table.codePointTable.isEmpty)
            assert(table.dataTable.isEmpty)
            table.codePointTable.append(UInt16(truncatingIfNeeded: planeRange.lowerBound))
            table.dataTable.append(Schema.entry(data, copyForStartingAt: planeRange.lowerBound))
            return true
          }
          if planeRange.contains(codePoints.lowerBound) {
            // Add this data to an existing plane table.
            assert(table.codePointTable.isEmpty == false || codePoints.lowerBound == 0x80)
            assert(table.dataTable.isEmpty == false || codePoints.lowerBound == 0x80)
            table.codePointTable.append(UInt16(truncatingIfNeeded: codePoints.lowerBound))
            table.dataTable.append(data)
            return true
          }
          // Data does not belong in this plane at all.
          return false
        }

        var wasInsertedAtLeastOnce = false

        // - Add the data value for any parts of the range which lie within the BMP.

        if codePoints.lowerBound < 0x1_0000 {
          for subPlane in 0x00...0x0F {
            let subplaneStart = UInt32(subPlane) << 12
            let subplaneRange = subplaneStart...subplaneStart + 0x0FFF
            if addToPlaneTable(&db._bmpData[subPlane], planeRange: subplaneRange) { wasInsertedAtLeastOnce = true }
          }
        }

        // - Add the data value for any parts of the range which lie above the BMP.

        for plane in 1..<17 {
          let planeStart = UInt32(plane) << 16
          let planeRange = planeStart...planeStart + 0xFFFF
          if addToPlaneTable(&db._nonbmpData[plane - 1], planeRange: planeRange) { wasInsertedAtLeastOnce = true }
        }

        precondition(wasInsertedAtLeastOnce, "Entry was not inserted: \(data)")
      }
    }
  }


  // --------------------------------------------
  // MARK: - Printing
  // --------------------------------------------


  extension CodePointDatabase where Schema: CodePointDatabaseBuildSchema {

    /// Returns a String of this database as Swift source code.
    ///
    /// The `name` parameter is used as a prefix for the various internal tables.
    ///
    internal func printAsSwiftSourceCode(name: String) -> String {

      var output = ""

      // ASCII.

      printArrayLiteral(
        name: "\(name)_ascii",
        elementType: Schema.asciiEntryElementType,
        data: _asciiData, columns: 8,
        formatter: Schema.formatASCIIEntry,
        to: &output
      )
      output += "\n"

      // BMP.

      Self.printPlaneData(
        name: name + "_bmp",
        tableData: _bmpData,
        to: &output
      )
      output += "\n"

      // Non-BMP.

      Self.printPlaneData(
        name: name + "_nonbmp",
        tableData: _nonbmpData,
        to: &output
      )

      return output
    }

    private static func printPlaneData(
      name: String,
      tableData: [SplitTable<UInt16, Schema.UnicodeData>],
      to output: inout String
    ) {

      // Print each split table separately.

      var subTables = [(String, String)]()
      for (plane, data) in tableData.enumerated() {
        let codePointTableName = "\(name)_\(plane)"
        let dataTableName = "\(name)_data_\(plane)"

        printArrayLiteral(
          name: codePointTableName,
          elementType: "UInt16",
          data: data.codePointTable, columns: 10,
          formatter: { $0.hexString(format: .fullWidth) },
          to: &output
        )
        output += "\n"

        printArrayLiteral(
          name: dataTableName,
          elementType: Schema.unicodeEntryElementType,
          data: data.dataTable, columns: 8,
          formatter: Schema.formatUnicodeEntry,
          to: &output
        )
        output += "\n"

        subTables.append((codePointTableName, dataTableName))
      }

      // Print an overall "_splitTables" array for recombining as a CodePointDatabase.

      printArrayLiteral(
        name: "\(name)_splitTables",
        elementType: "(codePointTable: [UInt16], dataTable: [\(Schema.unicodeEntryElementType)])",
        data: subTables, columns: 1,
        formatter: { "(codePointTable: \($0.0), dataTable: \($0.1))" },
        to: &output
      )
    }
  }

#endif  // UNICODE_DB_INCLUDE_BUILDER
