#if !canImport(ObjectiveC)
import XCTest

extension BaseTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BaseTests = [
        ("testExample", testExample),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(BaseTests.__allTests__BaseTests),
    ]
}
#endif
