name: Swift package tests (macOS)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-11

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build -v
    - name: Run tests
      run: SWIFT_URL_REPORT_PATH=/private/var/tmp/swift-url-report/ swift test -v
    - name: Build benchmarks
      run: |
        cd Benchmarks
        swift build -v
    - name: Upload report files
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: test-reports
        path: /private/var/tmp/swift-url-report/*
        if-no-files-found: warn
